# Generated by Django 3.0.7 on 2020-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('title', models.CharField(default='Default Title', max_length=200)),
                ('file', models.FileField(default='input-files/DEFAULT_Outline_0_000.txt', upload_to='input-files/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
